application: semantictwitter
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /hypertwitter.png
  static_files: static/hypertwitter.png
  upload: static/hypertwitter.png 
   
- url: /test.css
  static_files: static/test.css
  upload: static/test.css

- url: /logo_unibw.gif
  static_files: static/logo_unibw.gif
  upload: static/logo_unibw.gif

- url: /logo_ebusiness.gif
  static_files: static/logo_ebusiness.gif
  upload: static/logo_ebusiness.gif
                            
- url: .*
  script: main.py 
  


  

